<?php
require_once '/../database/baseDatos.php';
include_once '/../model/Artista.php';

class Artista_BD extends Artista
{
    private $base;

    public function Artista_BD(){}
    public function _construct($id, $nom, $arch, $est)
    {
        parent::_construct($id, $nom, $arch, $est); // TODO: Change the autogenerated stub

    }

    public function Guardar_Artista(){
        $base = new baseDatos();
        $sql = "insert into artista(a_nombre, a_archivo) values ('".$this->getNombre()."','".$this->getArchivo()."')";
        $base->consulta($sql);
    }

    public function Enviar_Resultado(){
        $base = new baseDatos();
        $sql = "select * from artista where a_estado = 1";
        $productos = $base->consulta($sql);
        $num_filas = $base->num_filas($productos);

        $filas = array();
        while ($arreglo = $base->fetch_array($productos)) {
             array_push($filas, $arreglo);     
        }
        return $filas;
        
    }
    public function Busqueda_Artista($artista){
        $base = new baseDatos();
        $sql = "select * from artista where a_nombre like '%".$artista."%' and a_estado = 1 ";
        $productos = $base->consulta($sql);
        $num_filas = $base->num_filas($productos);

        $filas = array();
        while ($arreglo = $base->fetch_array($productos)) {
          


             array_push($filas, $arreglo);     
        }
        return $filas;
        
    }

    public function Modificar_Artista($id){
        $base = new baseDatos();
        $sql = "Update artista set a_nombre='".$this->getNombre()."', a_archivo = '".$this->getArchivo()."' where a_id = ".$id; 
        $base->consulta($sql);
    }

    public function Eliminar_Artista($id){
        $base = new baseDatos();
        $sql = "Update artista set a_estado = 0 where a_id = ".$id; 
        $base->consulta($sql);
    }


}

?>